apiVersion: v1
kind: Service
metadata:
  name: audit-log
  labels:
    app.kubernetes.io/name: audit-log
    app.kubernetes.io/component: audit
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: audit-log
  ports:
    - name: http
      port: 8084
      targetPort: http
      protocol: TCP
      appProtocol: kubernetes.io/http
    - name: grpc
      port: 50054
      targetPort: grpc
      protocol: TCP
      appProtocol: kubernetes.io/h2c
