apiVersion: v1
kind: Service
metadata:
  name: console-backend-go
  labels:
    app.kubernetes.io/name: console-backend-go
    app.kubernetes.io/component: console-bff
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: console-backend-go
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
      appProtocol: kubernetes.io/http
