// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: datasourcemgr.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataSourceManagerService_Health_FullMethodName               = "/datasourcemgr.DataSourceManagerService/Health"
	DataSourceManagerService_ListDataSources_FullMethodName      = "/datasourcemgr.DataSourceManagerService/ListDataSources"
	DataSourceManagerService_GetDataSource_FullMethodName        = "/datasourcemgr.DataSourceManagerService/GetDataSource"
	DataSourceManagerService_CreateDataSource_FullMethodName     = "/datasourcemgr.DataSourceManagerService/CreateDataSource"
	DataSourceManagerService_UpdateDataSource_FullMethodName     = "/datasourcemgr.DataSourceManagerService/UpdateDataSource"
	DataSourceManagerService_DeleteDataSource_FullMethodName     = "/datasourcemgr.DataSourceManagerService/DeleteDataSource"
	DataSourceManagerService_TestConnection_FullMethodName       = "/datasourcemgr.DataSourceManagerService/TestConnection"
	DataSourceManagerService_GetMetadata_FullMethodName          = "/datasourcemgr.DataSourceManagerService/GetMetadata"
	DataSourceManagerService_GetDataSourceRecords_FullMethodName = "/datasourcemgr.DataSourceManagerService/GetDataSourceRecords"
	DataSourceManagerService_GetAccessAudit_FullMethodName       = "/datasourcemgr.DataSourceManagerService/GetAccessAudit"
	DataSourceManagerService_SeedDataSources_FullMethodName      = "/datasourcemgr.DataSourceManagerService/SeedDataSources"
)

// DataSourceManagerServiceClient is the client API for DataSourceManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataSourceManagerService 数据源管理与敏感特征自动探查 gRPC 服务
// DataSourceManagerService is the gRPC service interface for data source management and automated sensitive feature exploration.
type DataSourceManagerServiceClient interface {
	// Health 健康检查（自检 + 上游 Agent 连通性）
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// ListDataSources 获取已注册的数据源列表（支持分页）
	ListDataSources(ctx context.Context, in *ListDataSourcesRequest, opts ...grpc.CallOption) (*ListDataSourcesResponse, error)
	// GetDataSource 查询单个数据源详情
	GetDataSource(ctx context.Context, in *GetDataSourceRequest, opts ...grpc.CallOption) (*DataSourceProto, error)
	// CreateDataSource 注册新的数据源
	CreateDataSource(ctx context.Context, in *CreateDataSourceRequest, opts ...grpc.CallOption) (*DataSourceProto, error)
	// UpdateDataSource 更新数据源配置
	UpdateDataSource(ctx context.Context, in *UpdateDataSourceRequest, opts ...grpc.CallOption) (*DataSourceProto, error)
	// DeleteDataSource 删除数据源
	DeleteDataSource(ctx context.Context, in *DeleteDataSourceRequest, opts ...grpc.CallOption) (*DeleteDataSourceResponse, error)
	// TestConnection 测试数据源连通性
	TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error)
	// GetMetadata 获取数据源元数据与敏感字段自动探查分类结果
	GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error)
	// GetDataSourceRecords 读取数据源明细记录或采样数据
	GetDataSourceRecords(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (*GetRecordsResponse, error)
	// GetAccessAudit 查询数据源访问审计日志
	GetAccessAudit(ctx context.Context, in *GetAccessAuditRequest, opts ...grpc.CallOption) (*AccessAuditResponse, error)
	// SeedDataSources 初始化/预置默认样例数据源
	SeedDataSources(ctx context.Context, in *SeedDataSourcesRequest, opts ...grpc.CallOption) (*SeedDataSourcesResponse, error)
}

type dataSourceManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataSourceManagerServiceClient(cc grpc.ClientConnInterface) DataSourceManagerServiceClient {
	return &dataSourceManagerServiceClient{cc}
}

func (c *dataSourceManagerServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) ListDataSources(ctx context.Context, in *ListDataSourcesRequest, opts ...grpc.CallOption) (*ListDataSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDataSourcesResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_ListDataSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) GetDataSource(ctx context.Context, in *GetDataSourceRequest, opts ...grpc.CallOption) (*DataSourceProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataSourceProto)
	err := c.cc.Invoke(ctx, DataSourceManagerService_GetDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) CreateDataSource(ctx context.Context, in *CreateDataSourceRequest, opts ...grpc.CallOption) (*DataSourceProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataSourceProto)
	err := c.cc.Invoke(ctx, DataSourceManagerService_CreateDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) UpdateDataSource(ctx context.Context, in *UpdateDataSourceRequest, opts ...grpc.CallOption) (*DataSourceProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataSourceProto)
	err := c.cc.Invoke(ctx, DataSourceManagerService_UpdateDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) DeleteDataSource(ctx context.Context, in *DeleteDataSourceRequest, opts ...grpc.CallOption) (*DeleteDataSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDataSourceResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_DeleteDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestConnectionResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_TestConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_GetMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) GetDataSourceRecords(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (*GetRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecordsResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_GetDataSourceRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) GetAccessAudit(ctx context.Context, in *GetAccessAuditRequest, opts ...grpc.CallOption) (*AccessAuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessAuditResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_GetAccessAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceManagerServiceClient) SeedDataSources(ctx context.Context, in *SeedDataSourcesRequest, opts ...grpc.CallOption) (*SeedDataSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeedDataSourcesResponse)
	err := c.cc.Invoke(ctx, DataSourceManagerService_SeedDataSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataSourceManagerServiceServer is the server API for DataSourceManagerService service.
// All implementations must embed UnimplementedDataSourceManagerServiceServer
// for forward compatibility.
//
// DataSourceManagerService 数据源管理与敏感特征自动探查 gRPC 服务
// DataSourceManagerService is the gRPC service interface for data source management and automated sensitive feature exploration.
type DataSourceManagerServiceServer interface {
	// Health 健康检查（自检 + 上游 Agent 连通性）
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// ListDataSources 获取已注册的数据源列表（支持分页）
	ListDataSources(context.Context, *ListDataSourcesRequest) (*ListDataSourcesResponse, error)
	// GetDataSource 查询单个数据源详情
	GetDataSource(context.Context, *GetDataSourceRequest) (*DataSourceProto, error)
	// CreateDataSource 注册新的数据源
	CreateDataSource(context.Context, *CreateDataSourceRequest) (*DataSourceProto, error)
	// UpdateDataSource 更新数据源配置
	UpdateDataSource(context.Context, *UpdateDataSourceRequest) (*DataSourceProto, error)
	// DeleteDataSource 删除数据源
	DeleteDataSource(context.Context, *DeleteDataSourceRequest) (*DeleteDataSourceResponse, error)
	// TestConnection 测试数据源连通性
	TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error)
	// GetMetadata 获取数据源元数据与敏感字段自动探查分类结果
	GetMetadata(context.Context, *GetMetadataRequest) (*MetadataResponse, error)
	// GetDataSourceRecords 读取数据源明细记录或采样数据
	GetDataSourceRecords(context.Context, *GetRecordsRequest) (*GetRecordsResponse, error)
	// GetAccessAudit 查询数据源访问审计日志
	GetAccessAudit(context.Context, *GetAccessAuditRequest) (*AccessAuditResponse, error)
	// SeedDataSources 初始化/预置默认样例数据源
	SeedDataSources(context.Context, *SeedDataSourcesRequest) (*SeedDataSourcesResponse, error)
	mustEmbedUnimplementedDataSourceManagerServiceServer()
}

// UnimplementedDataSourceManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataSourceManagerServiceServer struct{}

func (UnimplementedDataSourceManagerServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) ListDataSources(context.Context, *ListDataSourcesRequest) (*ListDataSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDataSources not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) GetDataSource(context.Context, *GetDataSourceRequest) (*DataSourceProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataSource not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) CreateDataSource(context.Context, *CreateDataSourceRequest) (*DataSourceProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDataSource not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) UpdateDataSource(context.Context, *UpdateDataSourceRequest) (*DataSourceProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDataSource not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) DeleteDataSource(context.Context, *DeleteDataSourceRequest) (*DeleteDataSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDataSource not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestConnection not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) GetMetadata(context.Context, *GetMetadataRequest) (*MetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) GetDataSourceRecords(context.Context, *GetRecordsRequest) (*GetRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataSourceRecords not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) GetAccessAudit(context.Context, *GetAccessAuditRequest) (*AccessAuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessAudit not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) SeedDataSources(context.Context, *SeedDataSourcesRequest) (*SeedDataSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SeedDataSources not implemented")
}
func (UnimplementedDataSourceManagerServiceServer) mustEmbedUnimplementedDataSourceManagerServiceServer() {
}
func (UnimplementedDataSourceManagerServiceServer) testEmbeddedByValue() {}

// UnsafeDataSourceManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataSourceManagerServiceServer will
// result in compilation errors.
type UnsafeDataSourceManagerServiceServer interface {
	mustEmbedUnimplementedDataSourceManagerServiceServer()
}

func RegisterDataSourceManagerServiceServer(s grpc.ServiceRegistrar, srv DataSourceManagerServiceServer) {
	// If the following call pancis, it indicates UnimplementedDataSourceManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataSourceManagerService_ServiceDesc, srv)
}

func _DataSourceManagerService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_ListDataSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDataSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).ListDataSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_ListDataSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).ListDataSources(ctx, req.(*ListDataSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_GetDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).GetDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_GetDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).GetDataSource(ctx, req.(*GetDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_CreateDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).CreateDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_CreateDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).CreateDataSource(ctx, req.(*CreateDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_UpdateDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).UpdateDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_UpdateDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).UpdateDataSource(ctx, req.(*UpdateDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_DeleteDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).DeleteDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_DeleteDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).DeleteDataSource(ctx, req.(*DeleteDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_TestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).TestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_TestConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).TestConnection(ctx, req.(*TestConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_GetMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).GetMetadata(ctx, req.(*GetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_GetDataSourceRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).GetDataSourceRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_GetDataSourceRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).GetDataSourceRecords(ctx, req.(*GetRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_GetAccessAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).GetAccessAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_GetAccessAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).GetAccessAudit(ctx, req.(*GetAccessAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceManagerService_SeedDataSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeedDataSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceManagerServiceServer).SeedDataSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceManagerService_SeedDataSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceManagerServiceServer).SeedDataSources(ctx, req.(*SeedDataSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataSourceManagerService_ServiceDesc is the grpc.ServiceDesc for DataSourceManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataSourceManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datasourcemgr.DataSourceManagerService",
	HandlerType: (*DataSourceManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _DataSourceManagerService_Health_Handler,
		},
		{
			MethodName: "ListDataSources",
			Handler:    _DataSourceManagerService_ListDataSources_Handler,
		},
		{
			MethodName: "GetDataSource",
			Handler:    _DataSourceManagerService_GetDataSource_Handler,
		},
		{
			MethodName: "CreateDataSource",
			Handler:    _DataSourceManagerService_CreateDataSource_Handler,
		},
		{
			MethodName: "UpdateDataSource",
			Handler:    _DataSourceManagerService_UpdateDataSource_Handler,
		},
		{
			MethodName: "DeleteDataSource",
			Handler:    _DataSourceManagerService_DeleteDataSource_Handler,
		},
		{
			MethodName: "TestConnection",
			Handler:    _DataSourceManagerService_TestConnection_Handler,
		},
		{
			MethodName: "GetMetadata",
			Handler:    _DataSourceManagerService_GetMetadata_Handler,
		},
		{
			MethodName: "GetDataSourceRecords",
			Handler:    _DataSourceManagerService_GetDataSourceRecords_Handler,
		},
		{
			MethodName: "GetAccessAudit",
			Handler:    _DataSourceManagerService_GetAccessAudit_Handler,
		},
		{
			MethodName: "SeedDataSources",
			Handler:    _DataSourceManagerService_SeedDataSources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datasourcemgr.proto",
}
