apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-hub-data
  labels:
    app.kubernetes.io/name: service-hub
    app.kubernetes.io/component: scheduler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi