apiVersion: v1
kind: Service
metadata:
  name: service-hub
  labels:
    app.kubernetes.io/name: service-hub
    app.kubernetes.io/component: scheduler
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: service-hub
  ports:
    - name: http
      port: 8082
      targetPort: http
      protocol: TCP
      appProtocol: kubernetes.io/http
    - name: grpc
      port: 50052
      targetPort: grpc
      protocol: TCP
      appProtocol: kubernetes.io/h2c